### PR TITLE
Enable offline use for DiarizationPipeline and let users choose if they want to print suppress_numerals message.

### PR DESCRIPTION
**Pull request by utility-aagrawal**
Hi,

I have made a couple of changes that I think will be useful for others:

1) The first change is related to issue #674. Currently, Diarization pipeline doesn't have an option load model from a directory. I enabled that by following the tutorial here: "[Can I use gated models (and pipelines) offline?](https://github.com/pyannote/pyannote-audio/blob/develop/FAQ.md#can-i-use-gated-models-(and-pipelines)-offline)". In short, users can download the config.yaml and the pytorch model files from huggingface locally and use them in the pipeline.

2) Currently, when you enable suppress_numerals flag, a huge message is printed on the console. I introduced a flag so that users can choose if they want this print message or not.

Let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by GroovyDan** [comment]
@utility-aagrawal I believe you can already use the diarization pipeline offline by just specifying a local path to a `config.yaml` as the `model_name`:

diarize_model = whisperx.DiarizationPipeline(
    model_name=os.path.join(MODEL_DIR, DIARIZATION_FOLDER, "config.yaml"),
    device=DEVICE
)

**Comment by rimeikis** [comment]
> @utility-aagrawal I believe you can already use the diarization pipeline offline by just specifying a local path to a `config.yaml` as the `model_name`:
> 
> diarize_model = whisperx.DiarizationPipeline( model_name=os.path.join(MODEL_DIR, DIARIZATION_FOLDER, "config.yaml"), device=DEVICE )

Could you please elaborate? I used [this guide](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/applying_a_pipeline.ipynb) to download the config.yml and pytorch_model.bin files, but when I provide it in the model_name argument, I get an error: 
`
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name'
`

**Comment by GroovyDan** [comment]
@rimeikis What does your config.yml file look like? Have you updated it to point to the local pytorch_model.bin files you downloaded?

**Comment by utility-aagrawal** [comment]
@GroovyDan , you are right! I was able to load diarization model from local using your suggestion. Closing this PR. Thank you!

**Comment by digikar99** [comment]
> Have you updated it to point to the local pytorch_model.bin files you downloaded?

Could someone point out what exact change this is supposed to be?

**Comment by digikar99** [comment]
I suppose the following will be the new config.yaml:

```
pipeline:
  name: pyannote.audio.pipelines.VoiceActivityDetection
  params:
    segmentation: pytorch_model.bin

params:
  min_duration_off: 0.09791355693027545
  min_duration_on: 0.05537587440407595
  offset: 0.4806866463041527
  onset: 0.8104268538848918
```

I do run into errors with this, but I will double check and create an issue if required.

**Pull request closed without merging**
