### PR TITLE
Compatibility with the latest faster-whisper

### PR DESCRIPTION
**Pull request by latent-variable**

### CODE REVIEW

**Comment by M2ATrail** [comment]
for some reason it isn't using my gpu, can you please export conda env list? wanna see the actual requirements and what's installed.

**Comment by latent-variable** [comment]
@M2ATrail  did you do step 2 from the README. This is installed the required cuda requirements to utilize your gpu

**Comment by M2ATrail** [comment]
Yes, https://github.com/SYSTRAN/faster-whisper/issues/941

**Comment by M2ATrail** [comment]
@latent-variable pinging since idk if github notifies you.

**Comment by latent-variable** [comment]
@M2ATrail it looks faster whisper code got updated and its now broken,  I'll have to spend some time again updating this code to make it compatible with the latest version of faster whisper

**Comment by M2ATrail** [comment]
@latent-variable Alright, thanks, but I'd also appreciate if you share the env list output/pip req.

**Pull request closed without merging**
