### PR TITLE
Add Silero VAD as VAD model option; Add Faster-Whisper

### PR DESCRIPTION
**Pull request by cnbeining**
Replace #145 to free up `main` branch of my fork so I can do #121 .

Replace #147 .

### CODE REVIEW

**Comment by cnbeining** [comment]
CC @sailordiary

**Comment by databill86** [comment]
Any plans to merge this?

**Comment by m-bain** [comment]
@databill86 
yes its on my todo list, but v2 changed structure a lot so I cant merge this atm.
I see a need for faster-whisper, but I dont see the benefit of silero vs pyannote VAD. Also I need access to the raw detection scores for the min-cut operation.

**Comment by arnavmehta7** [comment]
@m-bain I have spent a lot of time with silero-vad. I find silero vad much more faster and have better output than pyannote VAD. Sometimes pyannote VAD fails to find the region whereas silero-vad almost everytime works. iirc score of silero-vad is also much better than pyannote vad

**Comment by corneliusgerico** [comment]
Thanks for your efforts. I'm also interested in Faster Whisper support.

**Comment by cnbeining** [comment]
Silero VAD support is added in Faster-Whisper. https://github.com/guillaumekln/faster-whisper

**Comment by corneliusgerico** [comment]
Sorry, I'm talking about Faster Whisper support in WhisperX per https://github.com/MahmoudAshraf97/whisper-diarization/issues/19#issuecomment-1500768750

**Pull request closed without merging**
