### PR TITLE
Fix memory issues

### PR DESCRIPTION
**Pull request by DaniruKun**
Ref: #89 

This PR fixes some issues with the alignment step.
The alignment model would be loaded too early, resulting in too much CUDA memory usage when both it and e.g. Whisper was loaded.
The solution was to load the alignment model lazily, and garbage collect Whisper and the VAD pipeline before doing any alignment work.

Added new flag `--gc_memory` which will try to gc unusued models and clean CUDA cache, off by default to keep backwards compatibility.

### CODE REVIEW

**Comment by m-bain** [comment]
Thanks for this, could you make this memory flush optional with a flag, since there is a tradeoff here of having to reload the models for every new audio file?

**Comment by DaniruKun** [comment]
@m-bain sonething like 'gc-memory'?

**Comment by m-bain** [comment]
> @m-bain sonething like 'gc-memory'?

Sure!

**Comment by DaniruKun** [comment]
@m-bain done, added as `--gc_memory`

**Comment by DaniruKun** [comment]
I will close for now in favor of #169

**Pull request closed without merging**
