### PR TITLE
feat: adding the docker file

### PR DESCRIPTION
**Pull request by SohaibAnwaar**
Add: 
1. Adding docker file

### CODE REVIEW

**Comment by m-bain** [comment]
nice, did you manage to try v3 btw?

**Comment by SohaibAnwaar** [comment]
No, I didn't try v3, But will definitely try. Thanks for merging my commit.

**Comment by m-bain** [comment]
v3 is now stable release so docker image would be helpful :)

**Comment by Juergen-J-F** [comment]
Agreed, would love a docker!

**Pull request merged**
