### PR TITLE
Added russian model

### PR DESCRIPTION
**Pull request by shigabeev**

### CODE REVIEW

**Comment by m-bain** [comment]
are 
`pyctcdecode
kenlm
`
packages required?

**Comment by shigabeev** [comment]
I remember the huggingface kindly asked me to install them and I just included them. I can try to remove them and see what happens. Give me 5 mins.

**Comment by shigabeev** [comment]
No, without pyctcdecode I get the following issue:
```
Wav2Vec2ProcessorWithLM requires the pyctcdecode library but it was not found in your environment. You can install it with pip:
`pip install pyctcdecode`. Please note that you may need to restart your runtime after installation.

Error loading model from huggingface, check https://huggingface.co/models for finetuned wav2vec2.0 models
```
and a traceback:

Screenshot 2023-01-14 at 10 31 04 AM

**Comment by shigabeev** [comment]
Here is what happens without KenLM
Screenshot 2023-01-14 at 10 36 45 AM

**Comment by MahmoudAshraf97** [comment]
Russian language was added in #53 so this might be closed

**Pull request closed without merging**
