### PR TITLE
Multiple improvements: language detection per segment, VAD min duration on/off, unique speakers, pyproject.toml and more.

### PR DESCRIPTION
**Pull request by cvl01**
WhisperX repo with multiple improvements combined: 

- Silero VAD added from #888 
- Diarization improvements from #590 
- Unique speakers added to result (inspiration from #126)
- Option to detect language per segment, very useful for longer audio with frequent language switches. 
- Changed `setup.py` to `pyproject.toml`
- Added VAD min duration on and off parameters to PyAnnote. The current implementation splits even on sub-second pauses which is rather ineffective sometimes. 
- Pyannote.audio bumped to 3.3.2

Feel free to check out my repo and suggest improvements.

### CODE REVIEW

**Review by 3manifold — CHANGES_REQUESTED** [review]
I doubt what the purpose of gathering multiple pull requests under a single pull request is (in addition, your commits are not dependent on commits regarding other pull requests) 😕. Please change this pull request & submit any changes relating only to your contribution.

**Comment by cvl01** [comment]
I agree with you in the sense that normally you'd open a pull request for one feature at once. 
Since this repo is unsupported I have created my own fork with all the changes that are useful for my personal whisperx usage. 
I did not create this with the intention of a pull request, more as a fully working, up to date whisperx package to be used in various projects. 
The reason I added the pull request here is for others to see the changes, and check out my repository if they want to see how it's implemented. 
If you insist, I can close the pull request. But since this repo is unmaintained and no new changes are merged in for a long time now, I don't think the extra effort of splitting into multiple PR's with one change/feature per PR is worth the effort.

**Comment by federicotorrielli** [comment]
Hi @cvl01, can you create PRs for my project? I plan to support WhisperX with the help of the community.

https://github.com/federicotorrielli/BetterWhisperX

**Comment by leinace1001** [comment]
Can you add max_speech_duration_s just as faster_whisper in VAD options? 
https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/vad.py

**Comment by Barabazs** [comment]
While I can understand your reasoning, this is highly unusual and actually makes further maintenance of the project harder. I will close this in favor of the original PR's.

Please feel free to recreate a PR with your improvements and try to limit a PR to a specific fix or enhancement.

**Pull request closed without merging**
