### PR TITLE
added Butterworth Bandpass filter, Normalization & Preemphasis filter

### PR DESCRIPTION
**Pull request by bunyaminergen**
Updated all data inputs to be of type Float32 and improved audio processing

The commit includes several changes in alignment.py, asr.py, audio.py, requirements.txt, and transcribe.py, primarily to enforce all data inputs to be of Float32 type for better compatibility with models and libraries used. In addition, improvements have been made to audio data processing through the inclusion of preemphasis, normalization and Butterworth Bandpass filters in the load_audio function in audio.py for clearer and more precise audio waveforms. Modified functions and in alignments, asr and transcribe.py were then updated to include these changes. Lastly, new versions of the dependencies were defined in requirements.txt for compatibility purposes.

### CODE REVIEW

**Comment by caryknoop** [comment]
This is great!

**Comment by m-bain** [comment]
Mm need to verify if this filtering actually helps across the board. What is the motivation for this?

**Comment by bunyaminergen** [comment]
Hello @m-bain,

The rationale behind adding filters is to enhance audio processing performance and ensure better compatibility with various models and libraries. The Butterworth Bandpass filter is intended to provide clarity by cutting off unwanted frequencies, while the preemphasis filter is aimed at increasing the intelligibility of speech signals. Normalization helps to maintain consistent and stable amplitude levels across audio data for the model to process more reliably. Preliminary results suggest these changes do indeed improve overall performance, but I understand the necessity for more comprehensive testing and data review.

Regarding the merge conflicts, I am willing to assist in resolving these and ensure smooth integration. If it's convenient for you, I will resolve the conflicts and resubmit the pull request for review.

Best regards,
Bunyamin Ergen

**Comment by bunyaminergen** [comment]
> Mm need to verify if this filtering actually helps across the board. What is the motivation for this?

Hello @m-bain,

The rationale behind adding filters is to enhance audio processing performance and ensure better compatibility with various models and libraries. The Butterworth Bandpass filter is intended to provide clarity by cutting off unwanted frequencies, while the preemphasis filter is aimed at increasing the intelligibility of speech signals. Normalization helps to maintain consistent and stable amplitude levels across audio data for the model to process more reliably. Preliminary results suggest these changes do indeed improve overall performance, but I understand the necessity for more comprehensive testing and data review.

Regarding the merge conflicts, I am willing to assist in resolving these and ensure smooth integration. If it's convenient for you, I will resolve the conflicts and resubmit the pull request for review.

Best regards,
Bunyamin Ergen

**Pull request closed without merging**
