### PR TITLE
Allow passing a function to FasterWhisperPipeline.transcribe()

### PR DESCRIPTION
**Pull request by b0vik**
This'll enable custom progress bar implementations, e.g.
```python3
import whisperx
import gc 

device = "cuda" 
audio_file = "example.webm"
batch_size = 8 # reduce if low on GPU mem
compute_type = "int8" # change to "int8" if low on GPU mem (may reduce accuracy)

model = whisperx.load_model("large-v2", device, compute_type=compute_type)

def testpf(progress):
    print(f"Current progress as a fraction: {progress}")

audio = whisperx.load_audio(audio_file)
result = model.transcribe(audio, batch_size=batch_size, combined_progress=True, progress_function=testpf)
print(result["segments"]) # before alignment
```
```bash
$ python3 test.py                                                                                                                                                           
Detected language: en (1.00) in first 30s of audio...                                                                                                                    
Current progress as a fraction: 0.03333333333333333                                                                                                                      
Current progress as a fraction: 0.06666666666666667                                                                                                                      
Current progress as a fraction: 0.1                                                                                                                                      
Current progress as a fraction: 0.13333333333333333                                                                                                                      
Current progress as a fraction: 0.16666666666666666
```

### CODE REVIEW

**Comment by casic** [comment]
And  what about  alignment and diarization ??  Can add  function for
progress ??

На нд, 7.01.2024 г. в 0:29 b0vik ***@***.***> написа:

**Comment by b0vik** [comment]
> And what about alignment and diarization ?? Can add function for progress ??  

Yeah, that's on me, sorry. I just added one for alignment. It doesn't look like `DiarizationPipeline` has an implementation for showing progress at the moment, so it'll be a bit less trivial to implement.

**Comment by stex** [comment]
I also added a PR for this which passes `current` and `total` instead of the already computed value in #620

**Comment by b0vik** [comment]
That's probably a better idea.

**Pull request closed without merging**
